### ISSUE TITLE
Required and nullable is ignored

### ISSUE THREAD

**Issue by JohnGalt1717** [Carapacik/swagger_parser#131]
Consider the following definition:

```
            "ArticleDto": {
                "required": [
                    "OriginalStoryBrokeOn",
                    "CreatedOn",
                    "UpdatedOn",
                    "IsActive",
                    "Tags",
                    "Categories",
                    "ConfidenceScore"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "format": "uuid",
                        "nullable": true
                    },
                    "title": {
                        "type": "string"
                    },
                    "synopsis": {
                        "type": "string"
                    },
                    "originalStoryBrokeOn": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "createdOn": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updatedOn": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "body": {
                        "type": "string"
                    },
                    "isActive": {
                        "type": "boolean"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "categories": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/ArticleCategories"
                        }
                    },
                    "country": {
                        "type": "string",
                        "nullable": true
                    },
                    "stateProvince": {
                        "type": "string",
                        "nullable": true
                    },
                    "city": {
                        "type": "string",
                        "nullable": true
                    },
                    "slug": {
                        "type": "string"
                    },
                    "confidenceScore": {
                        "type": "number",
                        "format": "float"
                    }
                },
                "additionalProperties": false
            },

```

It clearly defines what fields are required and nullable, but the generation doesn't use these, so everything is nullable when it really isn't.

**Comment by clragon** [comment]
I also experience this issue. 

Here is a minimal reproducible sample:

```yaml
{
  "openapi": "3.0.3",
  "info": {
    "title": "Parser Test",
    "description": "Parser Test",
    "version": "1.0.0"
  },
  "externalDocs": {
    "url": "/"
  },
  "servers": [],
  "tags": [],
  "paths": {},
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "nullable": true,
        "properties": {
          "a": {
            "type": "string",
            "nullable": false
          }
        }
      }
    },
    "examples": {}
  }
}
```

This snippet generates the following dart code:

```dart
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint

import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable()
class User {
  const User({
    this.a,
  });
  
  factory User.fromJson(Map<String, Object?> json) => _$UserFromJson(json);
  
  final String? a;

  Map<String, Object?> toJson() => _$UserToJson(this);
}
```

But for my understanding, this should actually mark `a` as `String` (and therefore `required`) instead of `String?`.

**Comment by Darkildo** [comment]
Can I somehow help solve the problem? Or someone is already doing this. Just a very critical thing...

**Comment by JohnGalt1717** [comment]
I already have the code and offered to do a pull request. I didn’t get a response.

**Comment by Carapacik** [comment]
Yes, I am work on it

**Comment by Carapacik** [comment]
@JohnGalt1717  @Darkildo Check branch 1.15
```yaml
  swagger_parser:
    git:
      url: https://github.com/Carapacik/swagger_parser
      ref: 1.15
      path: swagger_parser
```
