### ISSUE TITLE
Schemas doesn't inherits json_serializer

### ISSUE THREAD

**Issue by beerline** [Carapacik/swagger_parser#233]
### Steps to reproduce

1. define `json_serializer: freezed` in swagger_parser
2. define two schemas without `json_serializer`
3. run `dart run swagger_parser`

### Expected results

for both schemas should be generated **freezed** files

### Actual results

for both schemas generated `json_serializable `

### Your OpenApi snippet

```yaml
swagger_parser:
  output_directory: lib/core/api
  language: dart

  json_serializer: freezed

  required_by_default: true
  root_client: true
  export_file: true
  put_in_folder: true
  put_clients_in_folder: true
  path_method_name: true
  enums_to_json: true
  enums_parent_prefix: false
  unknown_enum_value: false
  mark_files_as_generated: true
  original_http_response: false

  schemes:
    - schema_path: api_schemas/fapi.json
      root_client_name: FApiClient
      output_directory: lib/core/api/fapi
      client_postfix: FApi

    - schema_path: api_schemas/credits_api.json
      root_client_name: CreditsClient
      name: CreditsApi
      output_directory: lib/core/api/credits_api
      client_postfix: Credits
```

### Logs

<details><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Dart version and used packages versions

<details><summary>Dart version</summary>

```console
Dart SDK version: 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "macos_x64"
```

</details><details><summary>Packages version</summary>

```console
swagger_parser: ^1.17.3
```

</details>
