### ISSUE TITLE
Model name suffix

### ISSUE THREAD

**Issue by BsBrabi** [Carapacik/swagger_parser#243]
### Use case

Currently the model classes get the name which are specified in the schema. It would be great if we can add a suffix to model name, so the names of the model classes do not clash with other classes in our app.

### Proposal

New configuration parameter `model_suffix` with default value set to an empty string.

Example:
```
swagger_parser:
  schema_url: https://petstore.swagger.io/v2/swagger.json
  output_directory: lib/api
  language: kotlin
  model_suffix: Dto
```
Model `Pet` will be named `PetDto`:
`data class PetDto(...)`

**Comment by StarProxima** [comment]
@BsBrabi You can use the `replacement_rules` config parameter to do this:
```yaml
  replacement_rules:
    - pattern: "$"
      replacement: "Dto"
 ```
