### ISSUE TITLE
Nullable enums in multipart/form-data requests

### ISSUE THREAD

**Issue by MartynasZabulionis** [Carapacik/swagger_parser#249]
### Steps to reproduce

Erroneous code is generated for **multipart/form-data** API requests which accept optional enum field. There is no check whether the provided enum argument is not null. Also enum itself, not it's String name is added to the fields map.

### Expected results

<img width="284" alt="image" src="https://github.com/user-attachments/assets/c7def5dd-36d0-4c4b-a20a-a46bf8c8377b">

### Actual results

<img width="277" alt="image" src="https://github.com/user-attachments/assets/7129ac87-5861-4979-bdd9-227cf7b670de">

### Dart version and used packages versions

Dart 3.4.3

```
dependencies:
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  openapi_generator_annotations: ^5.0.2
```

```
dev_dependencies:
  swagger_parser: ^1.18.0
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0 
  openapi_generator: ^5.0.2
```
