### ISSUE TITLE
Question: Do you have support for enum?

### ISSUE THREAD

**Issue by jascodes** [Carapacik/swagger_parser#25]
For me enums as the type i.e string in most case in swagger while the enum field being ignored.

**Comment by Carapacik** [comment]
Yes, we use enum.

**Comment by jascodes** [comment]
For instance the following schema
```
"UploadResponse": 
			{
                "type": "object",
                "properties": {
                    "user": {
                        "$ref": "#/components/schemas/User"
                    },
                    "id": {
                        "type": "number"
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "RESOURCES",
                            "MESSAGES",
                            "COVER_IMAGE"
                        ]
                    },
                    "file": {
                        "type": "string"
                    },
                    "originalName": {
                        "type": "string"
                    },
                    "mimetype": {
                        "type": "string"
                    },
                    "size": {
                        "type": "number"
                    }
                },
                "required": [
                    "id",
                    "type",
                    "file",
                    "originalName",
                    "mimetype",
                    "size"
                ]
            }
```

produces the following schema.
```
import 'package:json_annotation/json_annotation.dart';

import 'user.dart';

part 'upload_response.g.dart';

@JsonSerializable()
class UploadResponse {
  const UploadResponse({
    required this.id,
    required this.type,
    required this.file,
    required this.originalName,
    required this.mimetype,
    required this.size,
    this.user,
  });
  
  factory UploadResponse.fromJson(Map<String, dynamic> json) => _$UploadResponseFromJson(json);
  
  final User? user;
  final num id;
  final String type;
  final String file;
  final String originalName;
  final String mimetype;
  final num size;

  Map<String, dynamic> toJson() => _$UploadResponseToJson(this);
}
```

My pubspec
```
version: 0.0.1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  dio: ^5.0.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  swagger_parser: ^0.8.0

swagger_parser:
  schema_path: lib/glu.json # Required. Sets the OpenApi schema path directory for api definition
  output_directory: lib # Required. Sets output directory for generated files (api clients and models)
  language: dart # Optional. Sets the programming language. Current available languages are: dart, kotlin. Default: dart
  squish_clients: true # Optional. Set 'true' to put all clients in one folder. Default: false
  client_postfix: Repo # Optional. Set postfix for client folder and Class. Works if there is only a single class or `squish_clients` is true. Default: ApiClient
  freezed: false
```
