### ISSUE TITLE
Replacement rules don't apply to class in OpenAPI 2.0

### ISSUE THREAD

**Issue by mpkander** [Carapacik/swagger_parser#266]
### Steps to reproduce

Generate any OpenAPI 2.0 yaml/json file (snippet below). Add any replacement rule in config: for example, adding "Dto" for all classes: 

```yaml 
  replacement_rules:
    - pattern: "$"
      replacement: "Dto"
```

### Expected results

"Dto" has been added to all classes and enums.

### Actual results

"Dto" has been added to enums only. 

### Your OpenApi snippet

https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/yaml/petstore-expanded.yaml

### Dart version and used packages versions

<details><summary>Dart version</summary>

```console
3.5.3
```
