### ISSUE TITLE
Ability to filter output path and/or endpoint

### ISSUE THREAD

**Issue by Mezatsong** [Carapacik/swagger_parser#279]
### Use case

I am building a module of my api, and I just need few endpoint, about 10% of all api endpoint.
But now the swagger_parser generate all endpoint, which is not the the best case

### Proposal

in the swagger_parser.yaml, add some kind of keys like this

```yml
...
          exclude_paths:
            - "/cars/get"
          include_paths:
            - "/auth/user"
            - "/balance"
            - "/balance/transactions"
            - "/balance/withdrawals"
            - "/balance/withdrawal/requests"
            - "/deposit-payment/request-payment-link"
            - "/deposit-payment/payment-status/{uuid}"

```
