### ISSUE TITLE
Duplicate class generation when using discriminator with schema path type definitions

### ISSUE THREAD

**Issue by sheat-git** [Carapacik/swagger_parser#300]
### Steps to reproduce

1. Run `swagger_parser` with an OpenAPI schema that includes a discriminator with schema path type definitions
2. Execute `build_runner`
3. When running `flutter run`, the following error occurs:
```
Error (Xcode): lib/core/client/export.dart:13:1: Error: 'ItemA' is exported from both 'package:swagger_parser_bug/core/client/models/item_a.dart' and 'package:swagger_parser_bug/core/client/models/response_items_union.dart'.
```

This issue occurs because when using discriminators in the schema, the same class name is generated multiple times in different files, causing export conflicts.

### Expected results

The generator should use unique class names to avoid conflicts. Here's the expected output:

#### `item_a.dart`

```item_a.dart
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import

import 'package:freezed_annotation/freezed_annotation.dart';

import 'item_type.dart';

part 'item_a.freezed.dart';
part 'item_a.g.dart';

@Freezed()
class ItemA with _$ItemA {
  const factory ItemA({
    required ItemType type,
    required String a,
  }) = _ItemA;
  
  factory ItemA.fromJson(Map<String, Object?> json) => _$ItemAFromJson(json);
}
```

#### `response_items_union.dart`

Use distinct class names for the union types:

```response_items_union.dart
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import

import 'package:freezed_annotation/freezed_annotation.dart';

import 'item_type.dart';

part 'response_items_union.freezed.dart';
part 'response_items_union.g.dart';

@Freezed(unionKey: 'type')
sealed class ResponseItemsUnion with _$ResponseItemsUnion {
  @FreezedUnionValue('a')
  const factory ResponseItemsUnion.a({
    required ItemType type,
    required String a,
  }) = ResponseItemsUnionA;

  @FreezedUnionValue('b')
  const factory ResponseItemsUnion.b({
    required ItemType type,
    required String b,
  }) = ResponseItemsUnionB;

  @FreezedUnionValue('c')
  const factory ResponseItemsUnion.c({
    required ItemType type,
    required String c,
  }) = ResponseItemsUnionC;

 
  factory ResponseItemsUnion.fromJson(Map<String, Object?> json) => _$ResponseItemsUnionFromJson(json);
}
```

### Actual results

The swagger_parser generates duplicate class definitions for the same type in different files:

#### `item_a.dart`

```item_a.dart
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import

import 'package:freezed_annotation/freezed_annotation.dart';

import 'item_type.dart';

part 'item_a.freezed.dart';
part 'item_a.g.dart';

@Freezed()
class ItemA with _$ItemA {
  const factory ItemA({
    required ItemType type,
    required String a,
  }) = _ItemA;
  
  factory ItemA.fromJson(Map<String, Object?> json) => _$ItemAFromJson(json);
}
```

#### `response_items_union.dart`

The same `ItemA` class is generated again in this file:

```response_items_union.dart
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import

import 'package:freezed_annotation/freezed_annotation.dart';

import 'item_type.dart';

part 'response_items_union.freezed.dart';
part 'response_items_union.g.dart';

@Freezed(unionKey: 'type')
sealed class ResponseItemsUnion with _$ResponseItemsUnion {
  @FreezedUnionValue('a')
  const factory ResponseItemsUnion.a({
    required ItemType type,
    required String a,
  }) = ItemA;

  @FreezedUnionValue('b')
  const factory ResponseItemsUnion.b({
    required ItemType type,
    required String b,
  }) = ItemB;

  @FreezedUnionValue('c')
  const factory ResponseItemsUnion.c({
    required ItemType type,
    required String c,
  }) = ItemC;

 
  factory ResponseItemsUnion.fromJson(Map<String, Object?> json) => _$ResponseItemsUnionFromJson(json);
}
```

### Your OpenApi snippet

```yaml
openapi: 3.0.0
paths:
  /xxx:
    get:
      operationId: XXX
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
info:
  title: XXX API
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    ItemType:
      type: string
      enum:
        - a
        - b
        - c
    ItemA:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/ItemType"
        a:
          type: string
      required:
        - type
        - a
    ItemB:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/ItemType"
        b:
          type: string
      required:
        - type
        - b
    ItemC:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/ItemType"
        c:
          type: string
      required:
        - type
        - c
    Response:
      type: object
      properties:
        items:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/ItemA"
              - $ref: "#/components/schemas/ItemB"
              - $ref: "#/components/schemas/ItemC"
            discriminator:
              propertyName: type
              mapping:
                a: "#/components/schemas/ItemA"
                b: "#/components/schemas/ItemB"
                c: "#/components/schemas/ItemC"

```

### Configuration

<details><summary><code>swagger_parser.yaml</code></summary>

```yaml
swagger_parser:
  # You must provide the file path and/or url to the OpenApi schema.

  # Sets the OpenApi schema path directory for api definition.
  schema_path: swagger.yaml

  # Sets the url of the OpenApi schema
  # schema_url: https://petstore.swagger.io/v2/swagger.json

  # Required. Sets output directory for generated files (Clients and DTOs).
  output_directory: lib/core/client

  # Optional. Sets the programming language.
  # Current available languages are: dart, kotlin.
  language: dart

  # Optional (dart only).
  # Current available serializers are: 'json_serializable', 'freezed' and 'dart_mappable'.
  json_serializer: freezed

  # Optional (dart only). Set 'true' to generate root client
  # with interface and all clients instances.
  root_client: true

  # Optional (dart only). Set root client name
  root_client_name: ApiClient

  # Optional. Set default content-type for all requests
  default_content_type: "application/json"

  # Optional. Set API name for folder and export file (coming soon).
  # If not specified, the file name is used.
  name: null

  # Optional (dart only). Set 'true' to generate export file.
  export_file: true

  # Optional. Set to 'true' to put the all api in its folder.
  put_in_folder: false

  # Optional. Set 'true' to put all clients in clients folder.
  put_clients_in_folder: false

  # Optional. Set to 'true' to squash all clients in one client.
  squash_clients: false

  # Optional. Set to 'false' to not write the schema from the url to the schema file.
  schema_from_url_to_file: true

  # Optional. Set postfix for Client class and file.
  client_postfix: Client

  # Optional. Set 'true' to use only the endpoint path for the method name.
  # Set 'false' to use operationId
  path_method_name: false

  # Optional (dart only). Set 'true' to include toJson() in enums.
  # If set to false, serialization will use .name instead.
  enums_to_json: false

  # Optional. Set 'true' to set enum prefix from parent component.
  enums_parent_prefix: false

  # Optional (dart only). Set 'true' to maintain backwards compatibility
  # when adding new values on the backend.
  unknown_enum_value: false

  # Optional. Set 'false' to not put a comment at the beginning of the generated files.
  mark_files_as_generated: true

  # Optional. Set regex replacement rules for the names of the generated classes/enums.
  # All rules are applied in order.
  replacement_rules:
    # Example of rule
    # - pattern: "[0-9]+"
    #   replacement: ""

  # Optional. You can pass a list of schemes.
  # Each schema inherits the parameters described in swagger_parser,
  # any parameter for any schema can be set manually.
  # Cannot be used at the same time as schema_path.

```

</details>

### Dart version and used packages versions

<details><summary>Dart version</summary>

```console
Dart SDK version: 3.7.0 (stable) (Wed Feb 5 04:53:58 2025 -0800) on "macos_arm64"
```

</details><details><summary>Packages version</summary>

```yaml
dependencies:
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
dev_dependencies:
  swagger_parser: 1.21.3
  json_serializable: 6.9.4
  retrofit_generator: 9.1.9
  freezed: 2.5.8
  build_runner: 2.4.15
```

</details>
