### ISSUE TITLE
Wrong JsonKey generated

### ISSUE THREAD

**Issue by winren9** [Carapacik/swagger_parser#309]
### Steps to reproduce

generate Swagger with the following config:
```
swagger_parser:
  enums_to_json: true
  schema_path: api.json 
  output_directory: lib/api 
  language: dart Default: dart
  json_serializer: freezed

global_options:
 freezed:
   runs_before:
     - json_serializable
 json_serializable:
   runs_before:
     - retrofit_generator
```

The JsonKey is wrong. It should start with a lowercase letter or even be omitted.
I checked the previous versions and it seems to be related to the 1.18.0 version

### Expected results

```
@Freezed()
class MenuItem with _$MenuItem {
  const factory MenuItem({
    required String title,
    required LinkOptions linkOptions,
  }) = _MenuItem;
  
  factory MenuItem.fromJson(Map<String, Object?> json) => _$MenuItemFromJson(json);
}
```

### Actual results

```
@Freezed()
class MenuItem with _$MenuItem {
  const factory MenuItem({
    required String title,
    @JsonKey(name: 'LinkOptions')
    required LinkOptions linkOptions,
  }) = _MenuItem;
  
  factory MenuItem.fromJson(Map<String, Object?> json) => _$MenuItemFromJson(json);
}
```

### Your OpenApi snippet

```
  "components": {
    "schemas": {
      "MenuItem": {
        "type": "object",
        "required": ["title"],
        "properties": {
          "title": { "type": "string", "example": "Test 123" },
          "linkOptions": { "$ref": "#/components/schemas/linkOptions" }
        }
      },
      "linkOptions": {
        "type": "object",
        "required": ["type", "title"],
        "properties": {
          "type": {
            "enum": ["internal", "external"],
            "type": "string",
            "example": "internal"
          }
        }
      }
    }
  },
```

### Dart version and used packages versions

<details><summary>Dart version</summary>

```console
Dart 3.7.2
```

</details><details><summary>Packages version</summary>

```console
  swagger_parser: 1.22.0
```

</details>
