### ISSUE TITLE
[Question] Can I have multiple schemas?

### ISSUE THREAD

**Issue by dfdgsdfg** [Carapacik/swagger_parser#47]
Like below

```yaml
swagger_parser:
  - schema_path: assets/openapis/app_api.json
     output_directory: lib/data/sources/app_api
     client_postfix: AppApi
  
  - schema_path: assets/openapis/common_api.json
     output_directory: lib/data/sources/common_api
     client_postfix: CommonApi  
```
