### ISSUE TITLE
Output is invalid

### ISSUE THREAD

**Issue by phackwer** [Carapacik/swagger_parser#5]
Hi,

The output we had with your code became a bit invalid.

It's missing a .g.dart file and also missing the a private class:

![image](https://user-images.githubusercontent.com/4871786/206713414-c1ad530f-4ffb-42aa-870d-658c8c54e211.png)

Also the dependencies are not totally clear, could you map them? The output however, seems quite nice.

**Comment by Carapacik** [comment]
Hello @phackwer, thanks for this issue.
In order for the part `translation_controller.g.dart` and `_TranslationControllerClient` errors to disappear, you need to write dependencies like in example in your pubspec.yaml file like these:
```yaml
dependencies:
  dio: ^4.0.0
  json_annotation: ^4.7.0
  retrofit: ^3.3.0

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  retrofit_generator: ^4.2.0
  swagger_parser: ^0.3.0
```

And for type `object` in Future in need your full swagger.json file  or piece of your swagger'.json file with this request
